### ISSUE TITLE
Feedback on your project

### ISSUE THREAD

**Issue by Leda909** [fac30/Agency-Phoenix-Halimah#15]
- I would suggest to still work on the contact pop up /modal form's style for make it more visually clear
         - Suggestion to id = "contactForm" to maybe add display: flex & flex-direction: column;
         - then also play around with the class="modal-content", like background-color and maybe padding.
              
- Check out the "testimonial" section. It does not load me the arrow image etc. Maybe add some image to it, like who said it about your agency.

- The responsibility and the design really nice.

**Comment by halimahexe** [comment]
Thank you so much for your feedback! I thought we'd fixed the arrow image visibility but it still doesn't appear to work, bizarrely...
